name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install python=3.10
        conda install -c psi4 psi4
        conda install -c conda-forge 'jax>=0.4.19'
        conda install -c conda-forge 'jaxlib>=0.4.19'
        conda install -c conda-forge h5py
        pip install -e .
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
