name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install python=3.10
        conda config --set solver classic
        conda install conda-forge::psi4
        conda install conda-forge::jax
        conda install conda-forge::jaxlib
        conda install conda-forge::pybind11
        conda install conda-forge::eigen
        conda install conda-forge::hdf5
        conda install conda-forge::h5py
        pip install -e .
    - name: Build integrals
      shell: bash -l {0}
      run: |
        cd $GITHUB_WORKSPACE/quax/integrals
        make
        cd $GITHUB_WORKSPACE
    - name: Test with pytest
      run: |
        conda install pytest
        python -m pytest
